# Generated by Django 5.2.13 on 2026-04-26 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='-')),
                ('price', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='-')),
                ('video_url', models.CharField(blank=True, max_length=200, null=True)),
                ('file_attachment', models.CharField(blank=True, max_length=200, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.course')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.coursecontent')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('std', 'Siswa'), ('ast', 'Asisten')], default='std', max_length=3)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coursecontent')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coursemember')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coursecontent')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coursemember')),
            ],
        ),
    ]
